task: &task F3_AINR_Unet
save_root: &save_root H:/_result/ai_factory/model_zoo/ainr/baseline_20260209
# path: !join [*save_root, "/train"]
device: cuda
workers: 0
dtype: torch.float32

model:
  name: &model_name AinrUnet
  input_shapes:
    present: [1, 1, 3008, 4000]
    previous: [1, 1, 3008, 4000]

database:
  train:
    vimeo:
      name: vimeo
      enable: true
      batch_size: 16
      shuffle: true
      dataset: DatasetVimeo2Raw
      parameters:
        paths:
          - F:/database/vimeo_png/datasets/vimeo_train_sn-51769.yaml
        cam: O2S
        cvt_bits: 16
        frame_num: 7
        edge_mask_val: 1.0
        fix_sequence: false
        # record_bad_data: F:/database/vimeo_png/datasets/vimeo_train_sn-47062_bad_data.yaml
    control:
      name: control
      enable: false
      batch_size: 4
  eval:
    vimeo_iso-800:
      name: vimeo_iso-800
      enable: true
      batch_size: 16
      shuffle: false
      dataset: DatasetVimeo2Raw
      parameters:
        paths:
          # - F:/database/vimeo_png/datasets/vimeo_val_sn-200.yaml
          - F:/database/vimeo_png/datasets/vimeo_val_sn-523.yaml
        cam: O2S
        cvt_bits: 16
        frame_num: 3
        iso: 800
        fix_sequence: true
    vimeo_iso-1600:
      name: vimeo_iso-1600
      enable: true
      batch_size: 16
      shuffle: false
      dataset: DatasetVimeo2Raw
      parameters:
        paths:
          # - F:/database/vimeo_png/datasets/vimeo_val_sn-200.yaml
          - F:/database/vimeo_png/datasets/vimeo_val_sn-523.yaml
        cam: O2S
        cvt_bits: 16
        frame_num: 3
        iso: 1600
        fix_sequence: true
    vimeo_iso-3200:
      name: vimeo_iso-3200
      enable: true
      batch_size: 16
      shuffle: false
      dataset: DatasetVimeo2Raw
      parameters:
        paths:
          # - F:/database/vimeo_png/datasets/vimeo_val_sn-200.yaml
          - F:/database/vimeo_png/datasets/vimeo_val_sn-523.yaml
        cam: O2S
        cvt_bits: 16
        frame_num: 3
        iso: 3200
        fix_sequence: true
    control:
      name: control
      enable: false
      batch_size: 4
  test:
    o2s:
      name: o2s
      cam: O2S
      enable: true
      frame_num: 5
      database_loader: read_raw_from_folders
      parameters:
        paths:
          - F:/database/AINR_V600/TestData/O2S/normal_video/O2S/raw10/N10103_250414_01_O2S_OVX9100_Portrait
          - F:/database/AINR_V600/TestData/O2S/normal_video/O2S/raw10/N20103_250414_01_O2S_OVX9100_Portrait
          # - F:/database/AINR_V600/TestData/O2S/normal_video/O2S/

    control:
      name: control
      enable: false
      frame_num: 5
      database_loader: generate_control_scene_raw

train:
  iters: 100000  # 00
  ckpt:
  path:  !join_path [*save_root, "train"]
  evaluate_before_train: false
  losses:
    mse:
      enable: true
      at_iter:
        start: 0
        end:
      weight: 1.0
      denoise:
        enable: false
        weight: 0.3
    masked_mse:
      enable: true
      at_iter:
        start: 0
        end:
      weight: 1.0
      denoise:
        enable: false
        weight: 0.3
    pixel_l1:
      enable: true
      at_iter:
        start: 0
        end:
      weight: 1.0
      denoise:
        enable: true
        weight: 0.3
    masked_l1:
      enable: true
      at_iter:
        start: 0
        end:
      weight: 1.0
      denoise:
        enable: true
        weight: 0.3
    channel_l1:
      enable: false
      at_iter:
        start: 0
        end:
      weight: 1.0
      denoise:
        enable: true
        weight: 0.3
    smooth_l1:
      enable: false
      at_iter:
        start: 0
        end:
      weight: 1.0
      denoise:
        enable: true
        weight: 0.3
    gradient:
      enable: false
      at_iter:
        start: # 30000
        end:
      weight: 1.0
      params:
        magnitude_weight: 1.0
        phase_weight: 0.5
    color:
      enable: true
      at_iter:
        start: # 30000
        end:
      weight: 1.0
      params:
        pattern: RGGB
        phase_weight: 1.0
        contrast_weight: 1.0
        hsv_weight:
          - 1.0
          - 1.0
          - 0
        loss: torch.nn.MSELoss

  optimizer:
    name: AdamW
    params:
      lr: 0.001
      betas:
        - 0.9
        - 0.999
      eps: 1e-08
      weight_decay: 0.01
      amsgrad: false
  intervals:
    log: 10
    save: 1000
  vis:
    enable: true
    save2local: true
    save2db: false
    sample_per_db: 4
    frames: 3

eval:
  ckpt:
  path:  !join_path [*save_root, "eval"]
  metrics:
    psnr:
      enable: true
      params:
        dim: [1,2,3]
    pixel_l1:
      enable: true
      params:
        dim: [1,2,3]
    channel_l1:
      enable: true
      params:
        dim: [2,3]
  dominate_metrics: psnr
  intervals:
    log: 10
  vis:
    enable: true
    save2local: true
    save2db: false
    save_ratio: 0.1

infer:
  ckpt: H:/_result/ai_factory/model_zoo/ainr/baseline_20260202/train/ckpt/AinrUnet_00050000.pth
  path:  !join_path [*save_root, "infer", "AinrUnet_00050000"]

log:
  project_name: *task
  experiment_name: !join_string [*model_name, "_baseline"]
  config:
  log_dir: !join_path [*save_root, "train", "log"]
  use_trackio: true
  space_id:
  resume: never
