task: F3_AINR
save_root: H:/_result/ai_factory/model_zoo/ainr/20260105

database:
  train:
    vimeo:
      name: vimeo
      enable: true
      path: F:/database/vimeo_png/datasets/vimeo_val_sn-200.yaml
      batch_size: 16
    control:
      name: control
      enable: false
      batch_size: 4
  eval:
    vimeo:
      name: vimeo
      enable: true
      path: F:/database/vimeo_png/datasets/vimeo_val_sn-200.yaml
      batch_size: 16
    control:
      name: control
      enable: false
      batch_size: 4
  test:
    o2s:
      name: o2s
      enable: true
      path:
        - F:/database/AINR_V600/TestData/O2S/normal_video/O2S/
    control:
      name: control
      enable: false

train:
  ckpt:
  path: train
  optimizer:
    name: adamW
    params:
      lr: 0.001
      betas:
        - 0.9
        - 0.999
      eps: 1e-08
      weight_decay: 0.01
      amsgrad: false
  log:
    step: 10
  save:
    step: 100

eval:
  ckpt:
  path: eval
  metrics:

infer:
  ckpt:
  path: eval
