
name: CnnTransformerDecoder
input_shapes:
  present: [1, 3, 256, 256]
parameters:
  activation: &default_activation
    name: gelu
    parameters:
  arch:
    up_sample_params:
      in_channels: 16
      mid_channels:
      out_channels: &us_oc 16
      mode: up_sample
      activation:
        name: dyt
        parameters:
          normalized_shape: *us_oc
          channels_last: false
          alpha_init_value: 0.5
      bias: true
      pre_activation: false
      output_activation_disable: false
      in_front: true
      disable: false
    self_attn_block_params:
      in_channels: *us_oc
      mid_channels: 16
      bias: bool = True
    cross_attn_block_params:
      in_channels: *us_oc
      mid_channels: 16
      bias: bool = True
    mlp_params:
      in_channels: *us_oc
      mid_channels: 16
      bias: bool = True
