
name: AinrCnnTransformer
input_shapes:
  present: [1, 3, 256, 256]
parameters:
  arch:
    encoder:
      stage_0:
        conduct:
          attn_block_params:
            in_channels: &ic 3
            mid_channels: 16
            bias: bool = True
          mlp_params:
            in_channels: *ic
            mid_channels: 16
            bias: bool = True
          down_sample_params:
            in_channels: *ic
            mid_channels:
            out_channels: &encoder_stage0_ds_oc 32
            mode: keep_resolution
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: false
            disable: false
      stage_1:
        down:
          attn_block_params:
            in_channels: *encoder_stage0_ds_oc
            mid_channels: 32
            bias: bool = True
          mlp_params:
            in_channels: *encoder_stage0_ds_oc
            mid_channels: 32
            bias: bool = True
          down_sample_params:
            in_channels: *encoder_stage0_ds_oc
            mid_channels:
            out_channels: &encoder_stage1_ds_oc 64
            mode: down_sample
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: false
            disable: false
      stage_2:
        down:
          attn_block_params:
            in_channels: *encoder_stage1_ds_oc
            mid_channels: 64
            bias: bool = True
          mlp_params:
            in_channels: *encoder_stage1_ds_oc
            mid_channels: 64
            bias: bool = True
          down_sample_params:
            in_channels: *encoder_stage1_ds_oc
            mid_channels:
            out_channels: &encoder_stage2_ds_oc 128
            mode: down_sample
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: false
            disable: false
      stage_3:
        down:
          attn_block_params:
            in_channels: *encoder_stage2_ds_oc
            mid_channels: 128
            bias: bool = True
          mlp_params:
            in_channels: *encoder_stage2_ds_oc
            mid_channels: 128
            bias: bool = True
          down_sample_params:
            in_channels: *encoder_stage2_ds_oc
            mid_channels:
            out_channels: &encoder_stage3_ds_oc 256
            mode: down_sample
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: false
            disable: false
    mid_layer:
    decoder:
      stage3:
        up:
          attn_block_params:
            in_channels: *encoder_stage3_ds_oc
            mid_channels: 256
            bias: bool = True
          mlp_params:
            in_channels: *encoder_stage3_ds_oc
            mid_channels: 256
            bias: bool = True
          up_sample_params:
            in_channels: *encoder_stage3_ds_oc
            mid_channels:
            out_channels: &decoder_stage3_ds_oc 128
            mode: up_sample
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: false
            disable: false
      stage2:
        up:
          attn_block_params:
            in_channels: !math_add [*decoder_stage3_ds_oc, *encoder_stage2_ds_oc]
            mid_channels: 256
            bias: bool = True
          mlp_params:
            in_channels: !math_add [*decoder_stage3_ds_oc, *encoder_stage2_ds_oc]
            mid_channels: 256
            bias: bool = True
          up_sample_params:
            in_channels: !math_add [*decoder_stage3_ds_oc, *encoder_stage2_ds_oc]
            mid_channels:
            out_channels: &decoder_stage2_ds_oc 64
            mode: up_sample
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: false
            disable: false
      stage1:
        up:
          attn_block_params:
            in_channels: !math_add [*decoder_stage2_ds_oc, *encoder_stage1_ds_oc]
            mid_channels: 64
            bias: bool = True
          mlp_params:
            in_channels: !math_add [*decoder_stage2_ds_oc, *encoder_stage1_ds_oc]
            mid_channels: 64
            bias: bool = True
          up_sample_params:
            in_channels: !math_add [*decoder_stage2_ds_oc, *encoder_stage1_ds_oc]
            mid_channels:
            out_channels: &decoder_stage1_ds_oc 32
            mode: up_sample
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: false
            disable: false
      stage0:
        up:
          attn_block_params:
            in_channels: !math_add [*decoder_stage1_ds_oc, *encoder_stage0_ds_oc]
            mid_channels: 32
            bias: bool = True
          mlp_params:
            in_channels: !math_add [*decoder_stage1_ds_oc, *encoder_stage0_ds_oc]
            mid_channels: 32
            bias: bool = True
          up_sample_params:
            in_channels: !math_add [*decoder_stage1_ds_oc, *encoder_stage0_ds_oc]
            mid_channels:
            out_channels: &decoder_stage0_ds_oc 16
            mode: keep_resolution
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: false
            disable: false
    heads:
      head_denoise:
        in_channels: *decoder_stage0_ds_oc
        mid_channels:
        out_channels: 5
        activation:
            name: dyt
            parameters:
              normalized_shape: *decoder_stage0_ds_oc
              channels_last: false
              alpha_init_value: 0.5
        pre_activation: true
        output_activation_disable: True