
name: AinrUnetWithParamTuning
input_shapes:
  present: [1, 1, 3008, 4000]
  previous: [1, 1, 3008, 4000]
parameters:
  activation: &default_activation
    name: relu
    parameters:
  arch:
    width_scale: &width_scale 2
    adaptor:
      in_channels: 8
      mid_channels:
        - 8
      out_channels: &adaptor_oc !math_times [8, *width_scale]
      activation: *default_activation
    encoder:
      stage_0:
        in_channels: *adaptor_oc
        mid_channels:
          - !math_times [16, *width_scale]
        out_channels: &encoder_stage_0_oc !math_times [16, *width_scale]
        activation: *default_activation
      stage_1:
        in_channels: *encoder_stage_0_oc
        mid_channels:
          - !math_times [32, *width_scale]
        out_channels: &encoder_stage_1_oc !math_times [32, *width_scale]
        activation: *default_activation
      stage_2:
        in_channels: *encoder_stage_1_oc
        mid_channels:
          - 32
        out_channels: &encoder_stage_2_oc 32
        activation: *default_activation
    mid_layer:
    decoder:
      decoder_stage_2:
        in_channels: *encoder_stage_2_oc
        mid_channels:
          - !math_times [64, *width_scale]
        out_channels: &decoder_stage_2_oc !math_times [32, *width_scale]
        activation: *default_activation
      decoder_stage_1:
        in_channels: !math_add [*encoder_stage_1_oc, *decoder_stage_2_oc]
        mid_channels:
          - !math_times [32, *width_scale]
        out_channels: &decoder_stage_1_oc !math_times [16, *width_scale]
        activation: *default_activation
      decoder_stage_0:
        in_channels: !math_add [*encoder_stage_0_oc, *decoder_stage_1_oc]
        mid_channels:
          - !math_times [16, *width_scale]
        out_channels: &decoder_stage_0_oc !math_times [8, *width_scale]
        activation: *default_activation
    heads:
      head_denoise:
        in_channels: !math_add [*adaptor_oc, *decoder_stage_0_oc]
        mid_channels:
          - !math_times [8, *width_scale]
        out_channels: 5
        activation: *default_activation
        output_activation_disable: True