
name: AinrUnetTransformer
input_shapes:
  present: [1, 1, 3008, 4000]
  previous: [1, 1, 3008, 4000]
parameters:
  arch:
    encoder:
      stage_0:
        adaptor:
          self_attn_block_params:
            in_channels: &ic 8
            mid_channels: 16
            bias: bool = True
          mlp_params:
            in_channels: *ic
            mid_channels: 16
            bias: bool = True
          down_sample_params:
            in_channels: *ic
            mid_channels:
            out_channels: &encoder_stage0_mix_oc 16
            mode: keep_resolution
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: false
            disable: false
        conduct:
          self_attn_block_params:
            in_channels: *encoder_stage0_mix_oc
            mid_channels: &encoder_stage0_attn_mc 16
            bias: bool = True
          mlp_params:
            in_channels: *encoder_stage0_mix_oc
            mid_channels: 16
            bias: bool = True
          down_sample_params:
            in_channels: *encoder_stage0_mix_oc
            mid_channels:
            out_channels: &encoder_stage0_ds_oc 32
            mode: keep_resolution
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: false
            disable: false
      stage_1:
        conduct:
          self_attn_block_params:
            in_channels: *encoder_stage0_ds_oc
            mid_channels: 32
            bias: bool = True
          mlp_params:
            in_channels: *encoder_stage0_ds_oc
            mid_channels: 32
            bias: bool = True
          down_sample_params:
            in_channels: *encoder_stage0_ds_oc
            mid_channels:
            out_channels: &encoder_stage1_mix_oc 32
            mode: keep_resolution
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: false
            disable: false
        down:
          self_attn_block_params:
            in_channels: *encoder_stage1_mix_oc
            mid_channels: &encoder_stage1_attn_mc 32
            bias: bool = True
          mlp_params:
            in_channels: *encoder_stage1_mix_oc
            mid_channels: 32
            bias: bool = True
          down_sample_params:
            in_channels: *encoder_stage1_mix_oc
            mid_channels:
            out_channels: &encoder_stage1_ds_oc 64
            mode: down_sample
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: false
            disable: false
      stage_2:
        conduct:
          self_attn_block_params:
            in_channels: *encoder_stage1_ds_oc
            mid_channels: 64
            bias: bool = True
          mlp_params:
            in_channels: *encoder_stage1_ds_oc
            mid_channels: 64
            bias: bool = True
          down_sample_params:
            in_channels: *encoder_stage1_ds_oc
            mid_channels:
            out_channels: &encoder_stage2_mix_oc 64
            mode: keep_resolution
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: false
            disable: false
        down:
          self_attn_block_params:
            in_channels: *encoder_stage2_mix_oc
            mid_channels: &encoder_stage2_attn_mc 64
            bias: bool = True
          mlp_params:
            in_channels: *encoder_stage2_mix_oc
            mid_channels: 64
            bias: bool = True
          down_sample_params:
            in_channels: *encoder_stage2_mix_oc
            mid_channels:
            out_channels: &encoder_stage2_ds_oc 128
            mode: down_sample
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: false
            disable: false
      stage_3:
        conduct:
          self_attn_block_params:
            in_channels: *encoder_stage2_ds_oc
            mid_channels: 128
            bias: bool = True
          mlp_params:
            in_channels: *encoder_stage2_ds_oc
            mid_channels:  128
            bias: bool = True
          down_sample_params:
            in_channels: *encoder_stage2_ds_oc
            mid_channels:
            out_channels: &encoder_stage3_mix_oc 128
            mode: keep_resolution
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: false
            disable: false
        down:
          self_attn_block_params:
            in_channels: *encoder_stage3_mix_oc
            mid_channels: &encoder_stage3_attn_mc 128
            bias: bool = True
          mlp_params:
            in_channels: *encoder_stage3_mix_oc
            mid_channels: 128
            bias: bool = True
          down_sample_params:
            in_channels: *encoder_stage3_mix_oc
            mid_channels:
            out_channels: &encoder_stage3_ds_oc 256
            mode: down_sample
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: false
            disable: false
    mid_layer:
      in_channels: *encoder_stage3_ds_oc
      mid_channels:
        - 256
      out_channels: &mid_layer_oc 256
      activation:
            name: dyt
            parameters:
              normalized_shape: *mid_layer_oc
              channels_last: false
              alpha_init_value: 0.5
    decoder:
      stage3:
        up:
          up_sample_params:
            in_channels: *encoder_stage3_ds_oc
            mid_channels:
            out_channels: &decoder_stage3_us_oc 128
            mode: up_sample
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: true
            disable: false
          self_attn_block_params:
            in_channels: *decoder_stage3_us_oc
            mid_channels: 128
            bias: bool = True
          cross_attn_block_params:
            in_channels: *decoder_stage3_us_oc
            mid_channels: *encoder_stage3_attn_mc
            bias: bool = True
          mlp_params:
            in_channels: *decoder_stage3_us_oc
            mid_channels: 128
            bias: bool = True
        conduct:
          up_sample_params:
            in_channels: *decoder_stage3_us_oc
            mid_channels:
            out_channels: &decoder_stage3_oc 128
            mode: keep_resolution
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: true
            disable: false
          self_attn_block_params:
            in_channels: *decoder_stage3_oc
            mid_channels: 128
            bias: bool = True
          mlp_params:
            in_channels: *decoder_stage3_oc
            mid_channels: 128
            bias: bool = True
      stage2:
        up:
          up_sample_params:
            in_channels: *decoder_stage3_oc
            mid_channels:
            out_channels: &decoder_stage2_us_oc 64
            mode: up_sample
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: true
            disable: false
          self_attn_block_params:
            in_channels: *decoder_stage2_us_oc
            mid_channels: 64
            bias: bool = True
          cross_attn_block_params:
            in_channels: *decoder_stage2_us_oc
            mid_channels: *encoder_stage2_attn_mc
            bias: bool = True
          mlp_params:
            in_channels: *decoder_stage2_us_oc
            mid_channels: 64
            bias: bool = True
        conduct:
          up_sample_params:
            in_channels: *decoder_stage2_us_oc
            mid_channels:
            out_channels: &decoder_stage2_oc 64
            mode: keep_resolution
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: true
            disable: false
          self_attn_block_params:
            in_channels: *decoder_stage2_oc
            mid_channels: 64
            bias: bool = True
          mlp_params:
            in_channels: *decoder_stage2_oc
            mid_channels: 64
            bias: bool = True
      stage1:
        up:
          up_sample_params:
            in_channels: *decoder_stage2_oc
            mid_channels:
            out_channels: &decoder_stage1_us_oc 32
            mode: up_sample
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: true
            disable: false
          self_attn_block_params:
            in_channels: *decoder_stage1_us_oc
            mid_channels: 32
            bias: bool = True
          cross_attn_block_params:
            in_channels: *decoder_stage1_us_oc
            mid_channels: *encoder_stage1_attn_mc
            bias: bool = True
          mlp_params:
            in_channels: *decoder_stage1_us_oc
            mid_channels: 32
            bias: bool = True
        conduct:
          up_sample_params:
            in_channels: *decoder_stage1_us_oc
            mid_channels:
            out_channels: &decoder_stage1_oc 32
            mode: keep_resolution
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: true
            disable: false
          self_attn_block_params:
            in_channels: *decoder_stage1_oc
            mid_channels: 32  # 128
            bias: bool = True
          mlp_params:
            in_channels: *decoder_stage1_oc
            mid_channels: 32
            bias: bool = True
      stage0:
        cross_attn:
          up_sample_params:
            in_channels: *decoder_stage1_oc
            mid_channels:
            out_channels: &decoder_stage0_us_oc 16
            mode: keep_resolution
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: true
            disable: false
          self_attn_block_params:
            in_channels: *decoder_stage0_us_oc
            mid_channels: 16
            bias: bool = True
          cross_attn_block_params:
            in_channels: *decoder_stage0_us_oc
            mid_channels: *encoder_stage0_attn_mc
            bias: bool = True
          mlp_params:
            in_channels: *decoder_stage0_us_oc
            mid_channels: 16
            bias: bool = True
        conduct:
          up_sample_params:
            in_channels: *decoder_stage0_us_oc
            mid_channels:
            out_channels: &decoder_stage0_oc 16
            mode: keep_resolution
            activation:
            bias: true
            pre_activation: false
            output_activation_disable: false
            in_front: true
            disable: false
          self_attn_block_params:
            in_channels: *decoder_stage0_oc
            mid_channels: 16
            bias: bool = True
          mlp_params:
            in_channels: *decoder_stage0_oc
            mid_channels: 16
            bias: bool = True
    heads:
      head_denoise:
        in_channels: *decoder_stage0_oc
        mid_channels:
        out_channels: 5
        activation:
            name: dyt
            parameters:
              normalized_shape: *decoder_stage0_oc
              channels_last: false
              alpha_init_value: 0.5
        pre_activation: true
        output_activation_disable: True